#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
# I want to sync aex source!
    repo init -u https://github.com/NusantaraProject-ROM/android_manifest -b 11
#syncing repo
  repo sync -c --force-sync --no-tags --no-clone-bundle -j10(nproc --all)

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
# My local manifest can do all clone, and removing or changing repository i need, so lets use it! I am lazy to manually git clone!
git clone https://github.com/Realme-G95-Series/proprietary_vendor_realme_RMX2151.git vendor/realme/RMX2151 && git clone https://github.com/noobsauraj/device_realme_RMX2151 device/realme/RMX2151
